name: "Hello world action"
description: "Greeting"
inputs:
  name:
    description: "Name of the user"
    required: true
runs:
  using: composite
  steps:
    - name: "Print hello user"
      run: echo "Hello ${{ inputs.name }}"
      shell: bash


