name: Example use of custom action
on: push
jobs:
  Hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: my-action
        uses: ./.github/actions/hello-world
        with:
          name: Rohit
